job:run_master:
  script:
    - cp /root/env/.env back/.env
    - docker-compose kill
    - docker system prune -a -f
    - docker build front
    - docker-compose up -d --remove-orphans
  only:
    - master
