job:run_master:
  script:
    - cp -R /root/env/* .
    - docker-compose kill
    - docker system prune -a -f
    - docker build front
    - docker-compose up -d --remove-orphans
  only:
    - master
