job:run_master:
  script:
    - cp /root/env/.env back/.env
    - docker-compose kill
    - docker container prune -f
    - docker build front
    - docker build parser
    - docker-compose up -d --remove-orphans
  only:
    - master
