version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata/var/lib/postgresql/data
    ports:
      - "5432:5432"
  node:
    depends_on:
      - db
    image: node
    ports:
      - "4000:4000"