version: "3"
services:
  api:
    image: node:12.16.1
    container_name: api
    environment:
      NODE_ENV: production
      PORT: 3000
      DOCKER: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./back:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    command: "npm run dev"
  
  front:
    build: front
    container_name: vue
    depends_on:
      - api
    ports:
      - "8080:8080"
    links:
      - api

  python:
    build: parser
    container_name: parser
    volumes:
      - ./back/upload:/usr/app/upload
    ports:
      - "5000:5000"
    links:
      - api