version: "3"
services:
  back:
    image: node:12.16.1
    container_name: api
    environment:
      NODE_ENV: production
      PORT: 3000
      DOCKER: "true"
    volumes:
      - ./back:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    command: "npm run prod"
    ports:
      - "3000:3000"
  
  front:
    build: front
    container_name: vue
    environment:
      NODE_ENV: production
    depends_on:
      - back
    ports:
      - "80:5000"

  python:
    build: parser
    container_name: parser
    volumes:
      - ./back/upload:/usr/app/upload
