# Launch the API with a Posgre Server
version: "3"
services:
  api:
    image: node:12.16.1
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./back:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app
    command: "npm run dev"